### ISSUE TITLE
debian和centos怎样使用

### ISSUE THREAD

**Issue by mpv945** [HougeLangley/customkernel#1]
您好：
       看了您的视频，刚好最新项目需要开启ebpf内核参数，需要重新编译服务器运行的内核参数。看了您优化的点很有吸引力。就不知道您这个怎样编译安装呢？还要有没有针对vps和服务器的补丁集

**Comment by HougeLangley** [comment]
> 您好：
> 看了您的视频，刚好最新项目需要开启ebpf内核参数，需要重新编译服务器运行的内核参数。看了您优化的点很有吸引力。就不知道您这个怎样编译安装呢？还要有没有针对vps和服务器的补丁集

哈喽，首先非常感谢朋友的支持，哈哈

如果是Debian非常简单，朋友可以加入 Xanmod 的官方源就可以非常方便的通过 apt install 来安装 Xanmod 的内核，包括还有 Xanmod Cacule 的内核，另外里面还包含了RT 内核，已经长期支持版，地址在这里，朋友可以查看下：[Xanmod](https://xanmod.org)

如果朋友想在 Debian 中安装，BMQ或者是PDS的内核也非常方便，原作者有脚本直接跑就能通过编译安装出来，依赖等一套全部会解决，地址在这里：[Linux-TKg](https://github.com/Frogging-Family/linux-tkg)

如果在 Debian 下懒得编译也没事，哈哈，可以尝试 Liquorix 内核，它的地址在这里：[Liquorix](https://liquorix.net) 这个内核的特点酷似Linux-Tkg，不过因为使用的是 MuQSS，我个人觉得多线程的性能好像不如BMQ，不过这是个人感觉哈～

说完了 Debian，来说说 CentOS

CentOS目前有点尴尬，就是支持的比较少，早期确实有人搬运过去，后来（大概两三年前）我看脚本就停止更新了。也罢～或许我下一步来解决下呢（等我这期视频做完，嘿嘿）

上面是闲话。关于 Xanmod 我的思路是这样的，因为没有现成的rpm内核可以用，那么只有编译，其实解决也不困难用dnf/yum安装kernel的依赖，安装后，下载xanmod的内核源码，本地编译下打包成rpm然后安装。

如果是 Linux-tkg 会稍微好解决一些，朋友查看上面的链接的时候会注意到脚本中支持 Fedora，哈哈，是不是挺亲切。可以尝试能不能一键脚本搞定编译和安装。

目前以上是我的思路。

（或许我可以来打包 Debian 和 CentOS 呢）

后期我试试～

**Comment by mpv945** [comment]
感谢解答：
       我这边接触内核还不是很久，您的项目克隆到本地。我要怎样运行您的这个项目？我没看到.sh 直接脚本，是否还是进入到项目跟目录执行make && make install？您的这些都是基于Gentoo的内核吧？

**Comment by HougeLangley** [comment]
> 感谢解答：
> 我这边接触内核还不是很久，您的项目克隆到本地。我要怎样运行您的这个项目？我没看到.sh 直接脚本，是否还是进入到项目跟目录执行make && make install？您的这些都是基于Gentoo的内核吧？

目前我这个仓库里的是针对Gentoo的，朋友那边除非是Gentoo，如果是其他的发行版是弄不了的，我争取这个星期搞定Fedora和CentOS的打包。

目前朋友可以去看下上面那三个连接中的项目，可是试着玩一玩。

**Comment by HougeLangley** [comment]
> 感谢解答：
> 我这边接触内核还不是很久，您的项目克隆到本地。我要怎样运行您的这个项目？我没看到.sh 直接脚本，是否还是进入到项目跟目录执行make && make install？您的这些都是基于Gentoo的内核吧？

![image](https://user-images.githubusercontent.com/1161594/111797999-9d7cac00-8904-11eb-8c45-fef991ce43e2.png)
添加这个源就能安装 CentOS 8 Stream 的 Xanmod 内核了
