### ISSUE TITLE
XanMod-Kernel/  UKSM补丁如何在其他Linux上使用

### ISSUE THREAD

**Issue by ghost** [HougeLangley/customkernel#2]
最近想试试CRUX(crux.nu)
它要求安装完系统之后要手动编译内核

请问XanMod-UKSM如何编译
UKSM可不可以安装在Clear Linux 的内核

**Comment by HougeLangley** [comment]
你好，刚刚才看见你的消息。

是这样的，首先是确定你的发行版，如果朋友使用的是 Gentoo，那么编译这个内核非常容易，只需要 gentoo-zh 源添加到你的 gentoo overlay 中就可以了。安装的时候会提示相关 USE 来打开，一般而言，在 xanmod-hybird （gentoo中我是这么取得名字）需要选择 xanmod 和 cacule 两个 CPU 调度器，二选一就行，另外两个 cjktty 和 uksm，可以随便选。随后就是一些编译工作，因为默认的 config 已经包含在源码中，所以配置会方便一些。关于 uksm 的配置可以在内核配置界面（make nconfig 或者 make menuconfig 中都能看到），内存那个选项里是默认启动了 uksm 的，可以不用修改了。

那么谈到朋友提到的 clear linux 内核，这个应该是 Clear Linux 这个发行版，之前有关注过这个发行版，编译一些小软件我弄过，但是编译内核，我没有在上面试过，不过关于 Clear linux 的内核源码是放在 github 上的（当然还包括它的补丁），如果朋友想自己弄。我提供一个思路，我想应该是可以的。

1. 去了解下 Clean linux 下打包和编译的过程，如果朋友之前用过 Fedora 或者 CentOS 的话，这个应该不难；
2. 把 Clear Linux 最新的源码，或者朋友需要的源代码抓下来，包括它默认提供的补丁集；
3. 朋友关注下[这个 GitLab 的站点](https://gitlab.com/sirlucjan/kernel-patches/-/tree/master)，我都是从这里把修改和调整好的 UKSM 补丁移植到 Arch 和 Gentoo 的；
4. 下载朋友需要的，对应内核版本的 UKSM 补丁，在 Clear Linux 下编译安装应该就可以了。
5. 一般的，UKSM 补丁会自动默认（在配置内核选项的时候），只需要稍微关注下就可以了。

最后祝好运～

**Comment by HougeLangley** [comment]
如果朋友还有任何问题，再打开 issue @HougeLangley

**Comment by ghost** [comment]
你好
添加了overlay后下载好了（sys-kernel/xanmod-hybird xanmid uksm）
我是不是应该要在/usr/src里编译
请问，它的提示和选项怎么用
我如何在启动是正确引导，因为我启动系统后卡住了

工作顺利

在 2021年5月12日星期三，HougeLangley ***@***.***> 写道：
