### ISSUE TITLE
Xanmod Calcule bad gaming performance

### ISSUE THREAD

**Issue by moaalseiari** [HougeLangley/customkernel#3]
Hi. The gaming performance while using calcule use flag with xanmod-hybrid is bad. The system is slow. What is the recommended .config for intel users for the processor section? What is better 500hz or 1000hz? 
Kindly, do a gaming performance comparison between the kernels you are providing.

Thank you.

**Comment by HougeLangley** [comment]
Thanks for your reply.

I think default will good enough.

But, [comment out HZ_2000 from suggested configs. HZ_2000 added as an optio…](https://github.com/hamadmarri/cacule-cpu-scheduler/commit/7724955e6e47e2a4136719a9d834d9e4247f3b74) suggest 2000HZ

I think should waiting the new xanmod-cacule to merge this new feature.

**Comment by HougeLangley** [comment]
>
> But, [comment out HZ_2000 from suggested configs. HZ_2000 added as an optio…](https://github.com/hamadmarri/cacule-cpu-scheduler/commit/7724955e6e47e2a4136719a9d834d9e4247f3b74) suggest 2000HZ
> 

Sorry for my mistake, have no 2000HZ, I will try some benchmark as I could when I get home

**Comment by HougeLangley** [comment]
> Hi. The gaming performance while using calcule use flag with xanmod-hybrid is bad. The system is slow. What is the recommended .config for intel users for the processor section? What is better 500hz or 1000hz?
> Kindly, do a gaming performance comparison between the kernels you are providing.
> 
> Thank you.

Hi, friend, the new version have been released, Do you have test again?

**Comment by HougeLangley** [comment]
I will close this issue, if you have any trouble or question could tell me, I will try my best

**Comment by moaalseiari** [comment]
Have you done any performance testing? Which one and which .config settings your recommend for best performance for intel and nvidia systems? I have not upgrade the kernel yet but I will. I think the issue should be open to ensure transparency and support.

**Comment by HougeLangley** [comment]
I think I will, but for now I will test another thing first. So... OK, I will reopen it

**Comment by HougeLangley** [comment]
> Hi. The gaming performance while using calcule use flag with xanmod-hybrid is bad. The system is slow. What is the recommended .config for intel users for the processor section? What is better 500hz or 1000hz?
> Kindly, do a gaming performance comparison between the kernels you are providing.
> 
> Thank you.

I realize you ask what is the recommended .config. I curious the .config you used where and how to got?

**Comment by HougeLangley** [comment]
> Have you done any performance testing? Which one and which .config settings your recommend for best performance for intel and nvidia systems? I have not upgrade the kernel yet but I will. I think the issue should be open to ensure transparency and support. 

![IMG_20210628_230605.jpg](https://user-images.githubusercontent.com/1161594/123660130-f6de6a80-d865-11eb-9611-e77f307feeae.jpg)

![IMG_20210628_230628.jpg](https://user-images.githubusercontent.com/1161594/123660183-03fb5980-d866-11eb-8ca7-71e309387593.jpg)

![IMG_20210628_230658.jpg](https://user-images.githubusercontent.com/1161594/123660277-18d7ed00-d866-11eb-9aa1-4573074a26f5.jpg)

![IMG_20210628_230825.jpg](https://user-images.githubusercontent.com/1161594/123660342-28efcc80-d866-11eb-9413-c6f80ec7e4a0.jpg)

![IMG_20210628_230825.jpg](https://user-images.githubusercontent.com/1161594/123660404-360cbb80-d866-11eb-8846-8f715db65c80.jpg)

![IMG_20210628_230845.jpg](https://user-images.githubusercontent.com/1161594/123660452-3efd8d00-d866-11eb-994c-c5d71cf14742.jpg)

![IMG_20210628_231113.jpg](https://user-images.githubusercontent.com/1161594/123660487-4a50b880-d866-11eb-8c3a-ab9bc31fd790.jpg)

**Comment by HougeLangley** [comment]
@moaalseiari Hi, I know the reason.

![2021-07-01_13-54](https://user-images.githubusercontent.com/1161594/124263506-e8de6180-db65-11eb-9612-6b2c8d053f9a.png)

You maybe enable RDB and RDB load balancer, disable them will be good.

And do not using 2000 HZ, make 500HZ default will be fine.

**Comment by moaalseiari** [comment]
> @moaalseiari Hi, I know the reason.
> 
> ![2021-07-01_13-54](https://user-images.githubusercontent.com/1161594/124263506-e8de6180-db65-11eb-9612-6b2c8d053f9a.png)
> 
> You maybe enable RDB and RDB load balancer, disable them will be good.
> 
> And do not using 2000 HZ, make 500HZ default will be fine.

It is enabled in tkg calcule with different values. Thus, I do not think this is the reason friend. Maybe it is because of the additional patches other than xanmod patches.

**Comment by HougeLangley** [comment]
> > @moaalseiari Hi, I know the reason.
> > ![2021-07-01_13-54](https://user-images.githubusercontent.com/1161594/124263506-e8de6180-db65-11eb-9612-6b2c8d053f9a.png)
> > You maybe enable RDB and RDB load balancer, disable them will be good.
> > And do not using 2000 HZ, make 500HZ default will be fine.
> 
> It is enabled in tkg calcule with different values. Thus, I do not think this is the reason friend. Maybe it is because of the additional patches other than xanmod patches.

I make a video to compared the difference.

https://youtu.be/mNKXumLlxII
