### ISSUE TITLE
没事了，打扰了

### ISSUE THREAD

**Issue by halo-shit** [HougeLangley/customkernel#4]
抱歉，usbhub抽风影响到键盘了，虽然没有直接插在hub上，非常抱歉，删了这个issue吧😂

**Comment by HougeLangley** [comment]
你好，非常感谢支持。

请问下，是哪个内核，xanmod-hybrid 还是 linux-tkg 中的某个？看样子，朋友使用的是笔记本外接键盘的情况？

> 更新到13,开机usb键盘要重新把插才能用，降级回12就没问题

**Comment by halo-shit** [comment]
xanmod-cacule，笔记本

從我的 iPhone 傳送

**Comment by HougeLangley** [comment]
刚刚我在我的笔记本上测试了下，没有这个问题

**Comment by HougeLangley** [comment]
https://user-images.githubusercontent.com/1161594/123246533-798ac100-d518-11eb-9730-db8e78dfd4dc.mp4

**Comment by HougeLangley** [comment]
后来好了吗？还是怎么解决的？

**Comment by HougeLangley** [comment]
那我就关闭喽，如果有任何情况可以告诉我，我尽力帮你

**Comment by halo-shit** [comment]
> 后来好了吗？还是怎么解决的？

把插了所有usb设备就好了，给您添麻烦了
