### ISSUE TITLE
clang thinLTO链接时失败

### ISSUE THREAD

**Issue by halo-shit** [HougeLangley/customkernel#5]
LD      vmlinux
ld.lld: error: undefined symbol: hugetlb_basepage_index
>>> referenced by fbdev.c
>>>               vmlinux.o:(futex_get_bucket)
make: *** [Makefile:1200: vmlinux] Error 1

clang -v

clang version 12.0.0 (https://github.com/llvm/llvm-project ca55f0511698e5b64538e02eff9f6b2280282b15)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Selected GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Comment by HougeLangley** [comment]
朋友用 llvm 编译内核吗？配置文件是否切换成 CONFIG 下 clang 的 config ？

**Comment by halo-shit** [comment]
> 朋友用 llvm 编译内核吗？配置文件是否切换成 CONFIG 下 clang 的 config ？

用的是自己用了好久的config，试了下gcc也编译不过，提示
  LD      vmlinux
ld: kernel/futex2.o: in function `futex_get_bucket':
futex2.c:(.text+0x39a): undefined reference to `hugetlb_basepage_index'
make: *** [Makefile:1200: vmlinux] Error 1

**Comment by halo-shit** [comment]
另外试了下编译官方源的zen-sources-5.12，测试下环境和工具链，编译没有问题，不知道会不会是内核头文件的问题

**Comment by HougeLangley** [comment]
朋友有没有试过把它（xanmod）中提供的 config 提取出来和朋友你的做下 diff ，看看是哪里有区别～

这样我方便去给作者提意见或者issue，如果不用它默认的 config，xanmod 的开发者恐怕不认为是自己的问题。嘿嘿

**Comment by halo-shit** [comment]
> 朋友有没有试过把它（xanmod）中提供的 config 提取出来和朋友你的做下 diff ，看看是哪里有区别～
> 
> 这样我方便去给作者提意见或者issue，如果不用它默认的 config，xanmod 的开发者恐怕不认为是自己的问题。嘿嘿

make defconfig后编译通过了，可能5.13的config跟12的改动比较大？😂

**Comment by halo-shit** [comment]
很奇怪，不知道哪里依赖了HugeTLB fs，开了这个fs后，5.13也能编译通过了

**Comment by HougeLangley** [comment]
哈哈，这个是在 menuconfig 里面？

**Comment by halo-shit** [comment]
> 哈哈，这个是在 menuconfig 里面？

对，编译说找不到hugetlb_basepage_index符号，然后我就搜了下hugetlb相关的选项，开了hugetlb fs就得了😂

**Comment by HougeLangley** [comment]
哦，好呢，这个貌似是 clang 编译的时候才需要的是吧？

**Comment by HougeLangley** [comment]
我大概看了下 hugetlb ，在 xanmod 5.13 的 config 中默认是启用了
![2021-06-30_19-44](https://user-images.githubusercontent.com/1161594/123954993-adb02700-d9db-11eb-9457-e3ff6ba1a1ff.png)

**Comment by halo-shit** [comment]
> 我大概看了下 hugetlb ，在 xanmod 5.13 的 config 中默认是启用了
> ![2021-06-30_19-44](https://user-images.githubusercontent.com/1161594/123954993-adb02700-d9db-11eb-9457-e3ff6ba1a1ff.png)

很奇怪，上个版本不需要这个玩意，这个版本就要了。最近朋友推荐xandmod才用的侯哥的包，之前都是用zen-sources的，所以直接用了zen-sources配的config

**Comment by halo-shit** [comment]
> 哦，好呢，这个貌似是 clang 编译的时候才需要的是吧？

gcc也要，现在不用clang lto了，感觉玩dota2会内存泄漏

**Comment by HougeLangley** [comment]
哦哦，酱紫。对了，你自己使用下来，能否感觉的 clang 和 gcc 编译出来的内核有你能感觉到到提升，比方说某个软件运行效率更高或者整个桌面的响应更快？

**Comment by halo-shit** [comment]
> 哦哦，酱紫。对了，你自己使用下来，能否感觉的 clang 和 gcc 编译出来的内核有你能感觉到到提升，比方说某个软件运行效率更高或者整个桌面的响应更快？

速度没什么区别吧，因为用了固态，跑的又是bspwm。现在试一下dota2。

**Comment by HougeLangley** [comment]
哦，好的

**Comment by halo-shit** [comment]
> 哦，好的

无爱了，gcc版打dota2 使用6g内存加2g zram swap，8g内存有点顶不住，还是用clang lto吧😂

**Comment by HougeLangley** [comment]
哈哈，没想到 dota2 还挺吃内存

**Comment by halo-shit** [comment]
> 哈哈，没想到 dota2 还挺吃内存

前两年还是用4g内存打dota，现在8g也顶不住了，是时候加内存了。另外我dota2是跑在flatpak里的，系统纯64位，不知道flatpak runtime有没有额外的内存开销😂

**Comment by HougeLangley** [comment]
话说你用 gentoo 只用8g内存？

**Comment by halo-shit** [comment]
> 话说你用 gentoo 只用8g内存？

对啊，还是学生，电脑比较丐，我高中的时候用速龙1.9hz双核+1.5g内存的笔记本开始玩gentoo，上了大学才用现在这台好一点的笔记本，原本还是4g内存现在升级到8g。等工作了再换电脑。

**Comment by HougeLangley** [comment]
相当厉害了

**Comment by halo-shit** [comment]
> 相当厉害了

没有啦，就如肥猫苣巨说的，lfs才厉害，gentoo编译都是包管理器自动处理的 😂

**Comment by HougeLangley** [comment]
> > 相当厉害了
> 
> 没有啦，就如肥猫苣巨说的，lfs才厉害，gentoo编译都是包管理器自动处理的

是的，那个要自己手动维护，需要的工作量就更大了。更适合小型系统，或者注重性能和特性优化的，作为桌面光维护系统就要花不少时间。
