### ISSUE TITLE
5.14 uksm patch required

### ISSUE THREAD

**Issue by bigshans** [HougeLangley/customkernel#6]
The 5.14 version of uksm patch is not uploaded.

**Comment by HougeLangley** [comment]
Hi, I do think uksm no need to use anymore.

https://github.com/microcai/gentoo-zh/issues/1172

I send e-mail to @colo-ft who fix some errors in uksm, but no reply.

**Comment by bigshans** [comment]
Really Sad : (
But in arch, xanmod caucle has other problem. Recently, I will not update linux-xannomd-caucle-uksm until all problem is solved.

**Comment by HougeLangley** [comment]
> Really Sad : (
> But in arch, xanmod caucle has other problem. Recently, I will not update linux-xannomd-caucle-uksm until all problem is solved.

Don't be sad :P my friend. I will temporary remove, I will update that repo for a will.

**Comment by HougeLangley** [comment]
@bigshans Hi, I have been update, have a try :P ?

**Comment by bigshans** [comment]
The problem still have. The brightness is very low and can't adjust. May be related to the graphics card driver. I'm not sure whose problem is, I want to try again after arch releases v5.14. @HougeLangley

**Comment by HougeLangley** [comment]
AMD GPU or ?

**Comment by bigshans** [comment]
> AMD GPU or ?

Nvidia.

**Comment by HougeLangley** [comment]
> > AMD GPU or ?
> 
> Nvidia.

Have you try this ?

https://wiki.archlinux.org/title/NVIDIA_(简体中文)#启用亮度控制

**Comment by HougeLangley** [comment]
Do you use telegram?

**Comment by bigshans** [comment]
> Do you use telegram?

Yes.

**Comment by bigshans** [comment]
> > > AMD GPU or ?
> > 
> > 
> > Nvidia.
> 
> Have you try this ?
> 
> [https://wiki.archlinux.org/title/NVIDIA_(简体中文)#启用亮度控制](https://wiki.archlinux.org/title/NVIDIA_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#%E5%90%AF%E7%94%A8%E4%BA%AE%E5%BA%A6%E6%8E%A7%E5%88%B6)

It doesn't work.

**Comment by HougeLangley** [comment]
![image_2021-08-03_17-12-43](https://user-images.githubusercontent.com/1161594/132082466-f53a830b-8dfc-405c-baab-87073d5d6a1e.png)
![image_2021-08-03_17-16-34](https://user-images.githubusercontent.com/1161594/132082469-0fd89a7e-0f18-4029-87b9-6068dc9824a9.png)

Two way change backlight

**Comment by HougeLangley** [comment]
Second one is better.

**Comment by HougeLangley** [comment]
> > Do you use telegram?
> 
> Yes.

![2021-09-04_12-34_1](https://user-images.githubusercontent.com/1161594/132082517-317737f2-6192-4919-977f-17328b886579.png)

We could use IM :P

**Comment by bigshans** [comment]
> ![image_2021-08-03_17-12-43](https://user-images.githubusercontent.com/1161594/132082466-f53a830b-8dfc-405c-baab-87073d5d6a1e.png)
> ![image_2021-08-03_17-16-34](https://user-images.githubusercontent.com/1161594/132082469-0fd89a7e-0f18-4029-87b9-6068dc9824a9.png)
> 
> Two way change backlight

Don't work both. The new kernel does not find the nvidia driver.

**Comment by HougeLangley** [comment]
> > ![image_2021-08-03_17-12-43](https://user-images.githubusercontent.com/1161594/132082466-f53a830b-8dfc-405c-baab-87073d5d6a1e.png)
> > ![image_2021-08-03_17-16-34](https://user-images.githubusercontent.com/1161594/132082469-0fd89a7e-0f18-4029-87b9-6068dc9824a9.png)
> > Two way change backlight
> 
> Don't work both. The new kernel does not find the nvidia driver.

Use nvidia-dkms

**Comment by bigshans** [comment]
> > > ![image_2021-08-03_17-12-43](https://user-images.githubusercontent.com/1161594/132082466-f53a830b-8dfc-405c-baab-87073d5d6a1e.png)
> > > ![image_2021-08-03_17-16-34](https://user-images.githubusercontent.com/1161594/132082469-0fd89a7e-0f18-4029-87b9-6068dc9824a9.png)
> > > Two way change backlight
> > 
> > 
> > Don't work both. The new kernel does not find the nvidia driver.
> 
> Use nvidia-dkms

All test is installed.

**Comment by bigshans** [comment]
I guess it may be a problem with the v5.14 kernel, because the arch official has not yet released the v5.14 linux package, and it is still v5.13.13 . But I haven't tried the v5.13 version of xanmond-caucle yet, so I can only guess.

**Comment by HougeLangley** [comment]
> I guess it may be a problem with the v5.14 kernel, because the arch official has not yet released the v5.14 linux package, and it is still v5.13.13 . But I haven't tried the v5.13 version of xanmond-caucle yet, so I can only guess.

But, my arch install nvidia-dkms is fine

**Comment by bigshans** [comment]
> > I guess it may be a problem with the v5.14 kernel, because the arch official has not yet released the v5.14 linux package, and it is still v5.13.13 . But I haven't tried the v5.13 version of xanmond-caucle yet, so I can only guess.
> 
> But, my arch install nvidia-dkms is fine

Oh, I found it.

> If you find that changing the acpi_video0 backlight does not actually change the brightness, you may need to use acpi_backlight=none. 

It works. : )

**Comment by bigshans** [comment]
> Hi, I do think uksm no need to use anymore.
> 
> [microcai/gentoo-zh#1172](https://github.com/microcai/gentoo-zh/issues/1172)
> 
> I send e-mail to @colo-ft who fix some errors in uksm, but no reply.

How to trigger this bug?

**Comment by HougeLangley** [comment]
Win10 in KVM, Win10 will crash after boot a few minutes.

**Comment by bigshans** [comment]
> Win10 in KVM, Win10 will crash after boot a few minutes.

I am using it on a physical machine, but there is no crash.

**Comment by HougeLangley** [comment]
Linux guest in KVM will not crash. But if you check the dmesg of Host will see some messages like I saw.

**Comment by bigshans** [comment]
Yes, I confirmed.
