### ISSUE TITLE
貌似 cacule 也 archive 了。

### ISSUE THREAD

**Issue by bigshans** [HougeLangley/customkernel#7]
趋势上来看 tt 是要取代 cacule 了，到时候 README 也是要再改一下了。

**Comment by HougeLangley** [comment]
嗯嗯，我今天才发现这个 issue ，哈哈哈

**Comment by bigshans** [comment]
> 嗯嗯，我今天才发现这个 issue ，哈哈哈

> Xanmod vs Xanmod-TT ，但是大家注意，这里 Xanmod-tt 中使用的是实验性功能的 RDB CPU 调度器，所以性能表现不佳是完全可以理解的。

这里个地方就没必要了吧？链接实际上指向的是 xanmod vs xanmod-cacule ，而且改了之后后面也不太对了。

TT 也有自己的问题，[Is possible to use Docker Server with TT enabled in kernel?](https://github.com/hamadmarri/TT-CPU-Scheduler/issues/14) 。两全其美这种事总是很难的，如果不是很在意这些的话， TT 还是很好的。

**Comment by HougeLangley** [comment]
Update README.md, Done.
