### ISSUE TITLE
xanmod-hybrid  with use cacule patch fail

### ISSUE THREAD

**Issue by antonellocaroli** [HougeLangley/customkernel#8]
Hi,

there seems to be some problem in applying patches

Unfortunately, the log is quite long, so I'm only reporting part of it...

`>>> Source unpacked in /var/tmp/portage/sys-kernel/xanmod-hybrid-5.16.5/work
>>> Preparing source in /var/tmp/portage/sys-kernel/xanmod-hybrid-5.16.5/work/linux-5.16.5-xanmod ...
 * Applying patch-5.15.13-xanmod1-tt ...
patching file CONFIGS/xanmod/clang/config
patching file CONFIGS/xanmod/gcc/config
patching file Documentation/admin-guide/acpi/cppc_sysfs.rst
patching file Documentation/admin-guide/devices.txt
patching file Documentation/admin-guide/kernel-parameters.txt
Hunk #2 FAILED at 1694.
Hunk #3 FAILED at 2407.
Hunk #4 succeeded at 3360 (offset 30 lines).
Hunk #5 succeeded at 3924 (offset 30 lines).
Hunk #6 succeeded at 6417 with fuzz 2 (offset 57 lines).
2 out of 6 hunks FAILED -- saving rejects to file Documentation/admin-guide/kernel-parameters.txt.rej
patching file Documentation/admin-guide/pm/amd-pstate.rst
patching file Documentation/admin-guide/pm/working-state.rst
patching file Documentation/admin-guide/sysctl/kernel.rst
Hunk #1 FAILED at 1099.
1 out of 1 hunk FAILED -- saving rejects to file Documentation/admin-guide/sysctl/kernel.rst.rej
patching file Documentation/admin-guide/sysctl/vm.rst
patching file Documentation/dev-tools/kfence.rst
Hunk #1 FAILED at 231.
1 out of 1 hunk FAILED -- saving rejects to file Documentation/dev-tools/kfence.rst.rej
patching file Documentation/devicetree/bindings/iio/dac/adi,ad5766.yaml
Hunk #1 FAILED at 54.
1 out of 1 hunk FAILED -- saving rejects to file Documentation/devicetree/bindings/iio/dac/adi,ad5766.yaml.rej
patching file Documentation/devicetree/bindings/media/nxp,imx7-mipi-csi2.yaml
Hunk #1 FAILED at 79.
Hunk #2 FAILED at 91.
2 out of 2 hunks FAILED -- saving rejects to file Documentation/devicetree/bindings/media/nxp,imx7-mipi-csi2.yaml.rej
patching file Documentation/devicetree/bindings/net/ethernet-phy.yaml
Hunk #1 succeeded at 99 with fuzz 2 (offset 8 lines).
can't find file to patch at input line 23353
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/Documentation/devicetree/bindings/regulator/samsung,s5m8767.txt b/Documentation/devicetree/bindings/regulator/samsung,s5m8767.txt
|index 093edda0c8df..6cd83d920155 100644
|--- a/Documentation/devicetree/bindings/regulator/samsung,s5m8767.txt
|+++ b/Documentation/devicetree/bindings/regulator/samsung,s5m8767.txt
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
patching file Documentation/filesystems/fscrypt.rst
Hunk #1 FAILED at 176.
1 out of 1 hunk FAILED -- saving rejects to file Documentation/filesystems/fscrypt.rst.rej
patching file Documentation/hwmon/lm90.rst
Hunk #1 succeeded at 275 with fuzz 2 (offset 10 lines).
patching file Documentation/locking/locktypes.rst
Hunk #1 FAILED at 439.
Hunk #2 FAILED at 456.
2 out of 2 hunks FAILED -- saving rejects to file Documentation/locking/locktypes.rst.rej
patching file Documentation/networking/bonding.rst
Hunk #1 FAILED at 196.
1 out of 1 hunk FAILED -- saving rejects to file Documentation/networking/bonding.rst.rej
patching file Documentation/networking/device_drivers/ethernet/intel/ixgbe.rst
Hunk #1 succeeded at 456 with fuzz 2 (offset 16 lines).
patching file Documentation/networking/ipvs-sysctl.rst
`

**Comment by HougeLangley** [comment]
Hi, Thanks reply.

The reason is Xanmod upstream do not update xanmod-tt patch in xanmod 5.16.
