### ISSUE TITLE
Drop TT (CaCULe) Patch

### ISSUE THREAD

**Issue by HougeLangley** [HougeLangley/customkernel#9]
Long time not merge to xanmod 5.16

**Comment by antonellocaroli** [comment]
TT is an interesting patch, do you think it will not be developed anymore?

**Comment by HougeLangley** [comment]
> TT is an interesting patch, do you think it will not be developed anymore?

No, just wait a long time 🤔

**Comment by HougeLangley** [comment]
I think another way to keep xanmod-tt still here.
